/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/vitech-team/sdlcctl/apis/largetest/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLargeTestExecutions implements LargeTestExecutionInterface
type FakeLargeTestExecutions struct {
	Fake *FakeLargetestV1beta1
	ns   string
}

var largetestexecutionsResource = schema.GroupVersionResource{Group: "largetest", Version: "v1beta1", Resource: "largetestexecutions"}

var largetestexecutionsKind = schema.GroupVersionKind{Group: "largetest", Version: "v1beta1", Kind: "LargeTestExecution"}

// Get takes name of the largeTestExecution, and returns the corresponding largeTestExecution object, and an error if there is any.
func (c *FakeLargeTestExecutions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.LargeTestExecution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(largetestexecutionsResource, c.ns, name), &v1beta1.LargeTestExecution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LargeTestExecution), err
}

// List takes label and field selectors, and returns the list of LargeTestExecutions that match those selectors.
func (c *FakeLargeTestExecutions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.LargeTestExecutionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(largetestexecutionsResource, largetestexecutionsKind, c.ns, opts), &v1beta1.LargeTestExecutionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.LargeTestExecutionList{ListMeta: obj.(*v1beta1.LargeTestExecutionList).ListMeta}
	for _, item := range obj.(*v1beta1.LargeTestExecutionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested largeTestExecutions.
func (c *FakeLargeTestExecutions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(largetestexecutionsResource, c.ns, opts))

}

// Create takes the representation of a largeTestExecution and creates it.  Returns the server's representation of the largeTestExecution, and an error, if there is any.
func (c *FakeLargeTestExecutions) Create(ctx context.Context, largeTestExecution *v1beta1.LargeTestExecution, opts v1.CreateOptions) (result *v1beta1.LargeTestExecution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(largetestexecutionsResource, c.ns, largeTestExecution), &v1beta1.LargeTestExecution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LargeTestExecution), err
}

// Update takes the representation of a largeTestExecution and updates it. Returns the server's representation of the largeTestExecution, and an error, if there is any.
func (c *FakeLargeTestExecutions) Update(ctx context.Context, largeTestExecution *v1beta1.LargeTestExecution, opts v1.UpdateOptions) (result *v1beta1.LargeTestExecution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(largetestexecutionsResource, c.ns, largeTestExecution), &v1beta1.LargeTestExecution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LargeTestExecution), err
}

// Delete takes name of the largeTestExecution and deletes it. Returns an error if one occurs.
func (c *FakeLargeTestExecutions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(largetestexecutionsResource, c.ns, name), &v1beta1.LargeTestExecution{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLargeTestExecutions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(largetestexecutionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.LargeTestExecutionList{})
	return err
}

// Patch applies the patch and returns the patched largeTestExecution.
func (c *FakeLargeTestExecutions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.LargeTestExecution, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(largetestexecutionsResource, c.ns, name, pt, data, subresources...), &v1beta1.LargeTestExecution{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LargeTestExecution), err
}
