# permissions for end users to edit largetestexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: largetestexecution-editor-role
rules:
- apiGroups:
  - largetest.vitechteam.com
  resources:
  - largetestexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - largetest.vitechteam.com
  resources:
  - largetestexecutions/status
  verbs:
  - get
