# permissions for end users to view largetestexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: largetestexecution-viewer-role
rules:
- apiGroups:
  - largetest.vitechteam.com
  resources:
  - largetestexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - largetest.vitechteam.com
  resources:
  - largetestexecutions/status
  verbs:
  - get
