# permissions for end users to edit topologyrelease.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topologyrelease-editor-role
rules:
- apiGroups:
  - topologyrelease.vitechteam.com
  resources:
  - topologyrelease
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topologyrelease.vitechteam.com
  resources:
  - topologyrelease/status
  verbs:
  - get
