# permissions for end users to view topologyrelease.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topologyrelease-viewer-role
rules:
- apiGroups:
  - topologyrelease.vitechteam.com
  resources:
  - topologyrelease
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topologyrelease.vitechteam.com
  resources:
  - topologyrelease/status
  verbs:
  - get
