/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/vitech-team/sdlcctl/apis/topologyrelease/v1beta1"
	scheme "github.com/vitech-team/sdlcctl/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TopologyReleasesGetter has a method to return a TopologyReleaseInterface.
// A group's client should implement this interface.
type TopologyReleasesGetter interface {
	TopologyReleases(namespace string) TopologyReleaseInterface
}

// TopologyReleaseInterface has methods to work with TopologyRelease resources.
type TopologyReleaseInterface interface {
	Create(ctx context.Context, topologyRelease *v1beta1.TopologyRelease, opts v1.CreateOptions) (*v1beta1.TopologyRelease, error)
	Update(ctx context.Context, topologyRelease *v1beta1.TopologyRelease, opts v1.UpdateOptions) (*v1beta1.TopologyRelease, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.TopologyRelease, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.TopologyReleaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.TopologyRelease, err error)
	TopologyReleaseExpansion
}

// topologyReleases implements TopologyReleaseInterface
type topologyReleases struct {
	client rest.Interface
	ns     string
}

// newTopologyReleases returns a TopologyReleases
func newTopologyReleases(c *TopologyreleaseV1beta1Client, namespace string) *topologyReleases {
	return &topologyReleases{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the topologyRelease, and returns the corresponding topologyRelease object, and an error if there is any.
func (c *topologyReleases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.TopologyRelease, err error) {
	result = &v1beta1.TopologyRelease{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("topologyreleases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TopologyReleases that match those selectors.
func (c *topologyReleases) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.TopologyReleaseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.TopologyReleaseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("topologyreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested topologyReleases.
func (c *topologyReleases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("topologyreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a topologyRelease and creates it.  Returns the server's representation of the topologyRelease, and an error, if there is any.
func (c *topologyReleases) Create(ctx context.Context, topologyRelease *v1beta1.TopologyRelease, opts v1.CreateOptions) (result *v1beta1.TopologyRelease, err error) {
	result = &v1beta1.TopologyRelease{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("topologyreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(topologyRelease).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a topologyRelease and updates it. Returns the server's representation of the topologyRelease, and an error, if there is any.
func (c *topologyReleases) Update(ctx context.Context, topologyRelease *v1beta1.TopologyRelease, opts v1.UpdateOptions) (result *v1beta1.TopologyRelease, err error) {
	result = &v1beta1.TopologyRelease{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("topologyreleases").
		Name(topologyRelease.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(topologyRelease).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the topologyRelease and deletes it. Returns an error if one occurs.
func (c *topologyReleases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("topologyreleases").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *topologyReleases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("topologyreleases").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched topologyRelease.
func (c *topologyReleases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.TopologyRelease, err error) {
	result = &v1beta1.TopologyRelease{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("topologyreleases").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
