/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/vitech-team/sdlcctl/apis/largetest/v1beta1"
	scheme "github.com/vitech-team/sdlcctl/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LargeTestExecutionsGetter has a method to return a LargeTestExecutionInterface.
// A group's client should implement this interface.
type LargeTestExecutionsGetter interface {
	LargeTestExecutions(namespace string) LargeTestExecutionInterface
}

// LargeTestExecutionInterface has methods to work with LargeTestExecution resources.
type LargeTestExecutionInterface interface {
	Create(ctx context.Context, largeTestExecution *v1beta1.LargeTestExecution, opts v1.CreateOptions) (*v1beta1.LargeTestExecution, error)
	Update(ctx context.Context, largeTestExecution *v1beta1.LargeTestExecution, opts v1.UpdateOptions) (*v1beta1.LargeTestExecution, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.LargeTestExecution, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.LargeTestExecutionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.LargeTestExecution, err error)
	LargeTestExecutionExpansion
}

// largeTestExecutions implements LargeTestExecutionInterface
type largeTestExecutions struct {
	client rest.Interface
	ns     string
}

// newLargeTestExecutions returns a LargeTestExecutions
func newLargeTestExecutions(c *LargetestV1beta1Client, namespace string) *largeTestExecutions {
	return &largeTestExecutions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the largeTestExecution, and returns the corresponding largeTestExecution object, and an error if there is any.
func (c *largeTestExecutions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.LargeTestExecution, err error) {
	result = &v1beta1.LargeTestExecution{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("largetestexecutions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LargeTestExecutions that match those selectors.
func (c *largeTestExecutions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.LargeTestExecutionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.LargeTestExecutionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("largetestexecutions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested largeTestExecutions.
func (c *largeTestExecutions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("largetestexecutions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a largeTestExecution and creates it.  Returns the server's representation of the largeTestExecution, and an error, if there is any.
func (c *largeTestExecutions) Create(ctx context.Context, largeTestExecution *v1beta1.LargeTestExecution, opts v1.CreateOptions) (result *v1beta1.LargeTestExecution, err error) {
	result = &v1beta1.LargeTestExecution{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("largetestexecutions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(largeTestExecution).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a largeTestExecution and updates it. Returns the server's representation of the largeTestExecution, and an error, if there is any.
func (c *largeTestExecutions) Update(ctx context.Context, largeTestExecution *v1beta1.LargeTestExecution, opts v1.UpdateOptions) (result *v1beta1.LargeTestExecution, err error) {
	result = &v1beta1.LargeTestExecution{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("largetestexecutions").
		Name(largeTestExecution.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(largeTestExecution).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the largeTestExecution and deletes it. Returns an error if one occurs.
func (c *largeTestExecutions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("largetestexecutions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *largeTestExecutions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("largetestexecutions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched largeTestExecution.
func (c *largeTestExecutions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.LargeTestExecution, err error) {
	result = &v1beta1.LargeTestExecution{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("largetestexecutions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
